GO
USE olist_dataset


-- Shipping Days
ALTER TABLE olist_orders_dataset
ADD shipping_days AS 
DATEDIFF(DAY, order_purchase_timestamp, order_delivered_customer_date);


-- Weekday vs Weekend Flag
ALTER TABLE olist_orders_dataset
ADD day_type AS
CASE 
    WHEN DATENAME(WEEKDAY, order_purchase_timestamp) IN ('Saturday','Sunday')
    THEN 'Weekend'
    ELSE 'Weekday'
END;



-- KPI 1: Weekday vs Weekend Payment Statistics
SELECT 
    o.day_type,
    COUNT(DISTINCT p.order_id) AS total_orders,
    SUM(p.payment_value) AS total_payment,
    AVG(p.payment_value) AS avg_payment
FROM olist_orders_dataset o
JOIN olist_order_payments_dataset p
    ON o.order_id = p.order_id
GROUP BY o.day_type;


-- KPI 2: Orders with Review Score = 5 AND Payment Type = Credit Card
SELECT 
    COUNT(DISTINCT o.order_id) AS five_star_credit_orders
FROM olist_orders_dataset o
JOIN olist_order_reviews_dataset r
    ON o.order_id = r.order_id
JOIN olist_order_payments_dataset p
    ON o.order_id = p.order_id
WHERE r.review_score = 5
  AND p.payment_type = 'credit_card';



-- KPI 3: Avg Delivery Days for pet_shop Category
SELECT 
    AVG(DATEDIFF(DAY, o.order_purchase_timestamp, o.order_delivered_customer_date)) 
    AS avg_delivery_days
FROM olist_orders_dataset o
JOIN olist_order_items_dataset oi
    ON o.order_id = oi.order_id
JOIN olist_products_dataset pr
    ON oi.product_id = pr.product_id
WHERE pr.product_category_name = 'pet_shop'
  AND o.order_delivered_customer_date IS NOT NULL;



-- KPI 4: Avg Price & Payment for Customers from São Paulo
SELECT 
    AVG(oi.price) AS avg_product_price,
    AVG(p.payment_value) AS avg_payment_value
FROM olist_customers_dataset c
JOIN olist_orders_dataset o
    ON c.customer_id = o.customer_id
JOIN olist_order_items_dataset oi
    ON o.order_id = oi.order_id
JOIN olist_order_payments_dataset p
    ON o.order_id = p.order_id
WHERE LOWER(c.customer_city) = 'sao paulo';



-- KPI 5: Shipping Days vs Review Score (IMPORTANT KPI)
SELECT 
    r.review_score,
    AVG(DATEDIFF(DAY, o.order_purchase_timestamp, o.order_delivered_customer_date)) 
        AS avg_shipping_days,
    COUNT(*) AS total_orders
FROM olist_orders_dataset o
JOIN olist_order_reviews_dataset r
    ON o.order_id = r.order_id
WHERE o.order_delivered_customer_date IS NOT NULL
GROUP BY r.review_score
ORDER BY r.review_score;


-- top 5 sellers
SELECT TOP (5) [seller_id]
      ,[seller_zip_code_prefix]
      ,[seller_city]
      ,[seller_state]
  FROM olist_sellers_dataset


-- Seller Performance (Revenue)
SELECT 
    s.seller_id,
    SUM(oi.price) AS seller_revenue
FROM olist_order_items_dataset oi
JOIN olist_sellers_dataset s
    ON oi.seller_id = s.seller_id
GROUP BY s.seller_id
ORDER BY seller_revenue DESC;



-- Late Delivery Rate
SELECT 
    COUNT(*) * 100.0 / (SELECT COUNT(*) FROM olist_orders_dataset) AS late_delivery_percentage
FROM olist_orders_dataset
WHERE order_delivered_customer_date > order_estimated_delivery_date;



SELECT TOP (5) [customer_id]
      ,[customer_unique_id]
      ,[customer_zip_code_prefix]
      ,[customer_city]
      ,[customer_state]
FROM olist_customers_dataset


SELECT TOP (5) [geolocation_zip_code_prefix]
      ,[geolocation_lat]
      ,[geolocation_lng]
      ,[geolocation_city]
      ,[geolocation_state]
FROM olist_geolocation_dataset



SELECT TOP (5) [order_id]
      ,[payment_sequential]
      ,[payment_type]
      ,[payment_installments]
      ,[payment_value]
FROM olist_order_payments_dataset


--1)  What is the total revenue generated by Olist, and how has it changed over time?
-- to calculate the total revenue made by olist we have to add up total number of sales geenrated on the e-commerce olist data
-- Total revenue generated by Olist
SELECT ROUND(SUM(payment_value), 2) as "Total Revenue"  -- rounding the value to 2 decimal places
FROM olist_orders_dataset o
JOIN olist_order_payments_dataset p ON o.order_id = p.order_id --joining the orders and order_payments table
WHERE o.order_status != 'canceled' and o.order_status != 'unavailiable'  -- excluding the canceled and unavailiable status because the order did not geenrate any revenue to the company



--2) How many orders were placed on Olist, and how does this vary by month or season?
--How many orders were placed on Olist
SELECT COUNT(order_id) as orders_number
FROM olist_orders_dataset
WHERE order_status != 'canceled' AND order_status != 'unavailable'


--3) What is the average order value (AOV) on Olist, and how does this vary by product category or payment method?
-- AOV on olist
SELECT  ROUND(AVG(payment_value),2) AS Average_order_value
FROM olist_order_payments_dataset op
JOIN olist_orders_dataset od on op.order_id = od.order_id
WHERE order_status != 'canceled' AND order_status != 'unavailable'


-- how AOV varies by payment type
SELECT payment_type, ROUND(AVG(payment_value), 2) AS Average_order_value
FROM olist_order_payments_dataset op
JOIN olist_orders_dataset od on op.order_id = od.order_id
WHERE  order_status != 'canceled' AND order_status != 'unavailable'
GROUP BY payment_type
ORDER BY Average_order_value;


-- 4) What is the distribution of seller ratings on Olist, and how does this impact sales performance? 
-- Joining the order review dataset with the order payment dataset
SELECT
  oor.review_score,
  COUNT(DISTINCT oor.order_id) AS num_orders,
 ROUND(SUM(op.payment_value), 2) AS total_revenue,
  ROUND(AVG(op.payment_value), 2) AS avg_revenue
FROM olist_order_reviews_dataset oor
JOIN olist_order_payments_dataset op ON oor.order_id = op.order_id
GROUP BY oor.review_score
ORDER BY oor.review_score DESC;


-- 5) How many customers have made repeated purchases on Olist, and what percentage of total sales do they account for?
WITH repeated_customers AS (
    SELECT c.customer_unique_id, 
        COUNT(DISTINCT o.order_id) AS OrderCount, 
        ROUND(SUM(payment_value), 2) AS total_spent
    FROM olist_orders_dataset o
        INNER JOIN olist_customers_dataset c ON o.customer_id = c.customer_id
        INNER JOIN olist_order_payments_dataset oop ON o.order_id = oop.order_id
    GROUP BY c.customer_unique_id
    HAVING COUNT(DISTINCT o.order_id) > 1
)
SELECT COUNT(DISTINCT rc.customer_unique_id) AS num_repeated_customers,
    ROUND(SUM(rc.total_spent) / (SELECT SUM(payment_value) FROM olist_order_payments_dataset), 2) * 100 AS repeated_customer_sales_percentage,
    COUNT(DISTINCT c.customer_unique_id) AS total_customers,
    COUNT(DISTINCT c.customer_unique_id) - COUNT(DISTINCT rc.customer_unique_id) AS num_non_repeated_customers
FROM olist_customers_dataset c
LEFT JOIN repeated_customers rc ON c.customer_unique_id = rc.customer_unique_id;